### ISSUE TITLE
Laptop nvidia, on en est ou?

### ISSUE THREAD

**Issue by camini** [GLF-OS/Nixos-by-GLF#17]

**Comment by CORAAL** [comment]
Comme je l'ai mentionné [ici](https://github.com/GLF-OS/Nixos-by-GLF/issues/19#issuecomment-2543805799), sur un vieux laptop possédant un gpu nvidia, la détection automatique n'a pas fonctionné, j'ai dû manuellement activer l'option via : 

```nix
nvidia_config.enable = true;
```

La détection automatique n'a peut-être pas fonctionné sur mon matériel, peut-être qu'il aurait fonctionné sur un autre.

**Comment by CORAAL** [comment]
Comme vu sur le discord, la détection du gpu et la récupération de son adresse pci est basé sur le résultat de "lspci" dans la "section" VGA. 

Ma machine référence le GPU (discrete gpu) dans "3D". 

Autrement dit, la condition qui récupère l'adresse pci voit les gpu de la catégorie VGA mais pas 3D.
