### ISSUE TITLE
Suivis des retours de tests

### ISSUE THREAD

**Issue by CORAAL** [GLF-OS/Nixos-by-GLF#19]
ISO : `glfos-24.11.20241202.f9f0d5c-x86_64-linux`
Sortie : Lundi 09 Décembre 2024 21h52 | 20241209T2152

# Note de version : 

- [X] Supprimer le blocage en 32px de dash to dock
- [X] Supprimer:
  - [X] Xterm
  - [X] Thunderbird
  - [X] OBS
  - [X] Kdenlive
  - [X] GIMP
  - [X] Inkscape
- [X] Ajouter:
  - [X] Nix Helper (nh)
  - [X] LibreOffice
  - [X] Easy Flatpak
  - [X] Wallpaper GLF
- [X] Configurer GDM + Plymouth avec le logo GLF OS
- [X] Modifier le hostname par GLF par défaut
- [X] Modifier le kernel par défaut par kernel zen

# Bug connu 
Ces bugs ne sont pas nécessairement propre à l'iso mais peuvent apparaître, si vous en avez-un, informez-nous-en.
- (Pas un bug) : Easy flatpak est installé post installation, ça peut nécessiter un petit moment avant qu'il soit disponible.
Vous pouvez consulter sa progression avec :
```bash
sudo systemctl status flatpak-repo
```

--- 

Retour **Didic** (discord)

- [X] Supprimer le blocage en 32px de dash to dock -> J'ai pu le grossir donc j'imagine que c'est ok
- [X] Supprimer:
  - [X] Xterm
  - [X] Thunderbird
  - [X] OBS
  - [X] Kdenlive
  - [X] Gimp
  - [X] Inkscape
- [X] Ajouter:
  - [X] NH
  - [X] Libreoffice
  - [X] Easy Flatpak
 - [ ] Configurer GDM + Plymouth avec le logo GLF OS -> Je ne vois aucun logo au lancement de l'os et sur le choix des utilisateurs, j'ai le logo de nixos.
 - [X] Modifier le hostname par défaut de NixOS
 - [X] Basculer le kernel latest -> zen 

Observation supplémentaire : 

- Durant l'installation, les liens vers GLF Support pointent vers le projet NixOS et non GLF. (Tout les liens)

**Comment by CORAAL** [comment]
- Piaf Jaune: 

Modifier les images d'illustrations pour l'environnement de bureau par une illustration glf

**Comment by PiafJaune** [comment]
Pour Calamares, je compte 5 liens à revoir : 3 sur la première page (Bienvenue) et 2 sur la dernière (Terminer)

**Comment by camini** [comment]
Je vais pas revenir sur les points au dessus, tout est good sauf le point GDM/plymouth
Du coup j'ai fais l'install sur mon desktop avec la nvidia :
- Mes films de vacances ( :) ) en mkv ne passent pas sur totem . En AMD ca roule.
![Capture d’écran du 2024-12-10 20-21-04](https://github.com/user-attachments/assets/38e6e2dc-b935-484a-a300-ff91e6fbdee3)

**Comment by CORAAL** [comment]
> Je vais pas revenir sur les points au dessus, tout est good sauf le point GDM/plymouth Du coup j'ai fais l'install sur mon desktop avec la nvidia :
> 
>     * Mes films de vacances ( :) ) en mkv ne passent pas sur totem . En AMD ca roule.
>       ![Capture d’écran du 2024-12-10 20-21-04](https://private-user-images.githubusercontent.com/118620964/394419029-38e6e2dc-b935-484a-a300-ff91e6fbdee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NjU2MTUsIm5iZiI6MTczMzg2NTMxNSwicGF0aCI6Ii8xMTg2MjA5NjQvMzk0NDE5MDI5LTM4ZTZlMmRjLWI5MzUtNDg0YS1hMzAwLWZmOTFlNmZiZGVlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQyMTE1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmM2Y2RjNWExNTk2ZmFhYjYzYTRmZDcyNzQwZDliMTVmNzcwYzFkZWJlZDUwZThhNzBhNGU2MjRhYmNlOTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gqyrcPEAVaTwfGl2PNwbCY4DresA_Hau7VnmEVmQCHE)

Je note le même problème sur mon laptop nvidia avec totem qui n'utilise pas la configuration glf.
L'erreur apparaît lors du chargement de la vidéo (segmentation fault)

**Comment by CORAAL** [comment]
Test effectué sur : 

```
Lenovo Y70-70 Touch
CPU: Intel i7 4710HQ
GPU: Nvidia 860M
RAM: 8Go
Disque: 24.77 / 256Go
```

L'installation s'est déroulée sans accroc, en dehors de ce qui a déjà été dit voici quelques remarques : 

- Bug graphique avec mangohud durant le premier lancement de Steam (mangohud apparaît au-dessus de la fenêtre blanche de steam), rien de dramatique cependant, elle disparaît après quelques secondes.
- L'écran tactile a fonctionné dès le début. 
- Le pavé tactile est activé au démarrage
- Grub (sur un appareil "BIOS" et non pas UEFI) n'a pas de thème GLF, Plymouth et GDM non plus. 
- Steam arrive en anglais, proton, protong-ge déjà installé, mais nécessite d'être activé dans les paramètres d'un jeu avant d'être utilisé. 
- Nvidia n'a pas été installé par défaut, j'ai dû activer manuellement le module `nvidia_config.enable = true;`, suivis d'un rebuild puis d'un reboot, tout a fonctionné ensuite. 
- Le profil d'alimentation éteint l'écran après 5 minutes, mise en veille après 5 minutes
- Le laptop dispose d'un clavier rétro-éclairé qui a été reconnu dans gnome sans manipulation.
- NixHelper (nh) comme mentionné sur le discord ne permet pas de rebuild (une suggestion était d'indiquer le nix-path)
