### ISSUE TITLE
Build 10/12/2024 - Applications manquantes

### ISSUE THREAD

**Issue by T13nou** [GLF-OS/Nixos-by-GLF#35]
Hola,

Par rapport au cahier des charges, il me manque certaines applications

Contexte :

- ISO du 10/12/2024
- PC Full AMD (CPU 7900, GPU 7900XT)

Applications manquantes 
- OBS Studio
- Kdenlive
- Freetube
- Thunderbird
- Gimp
- Inkscape

**Comment by CORAAL** [comment]
Non, c'est bien correct, regarde le message que je t'ai envoyé (discord)

**Comment by T13nou** [comment]
Bien vu, je clos
