### ISSUE TITLE
Gnome Software contradiction dans la configuration

### ISSUE THREAD

**Issue by CORAAL** [GLF-OS/Nixos-by-GLF#38]
Dans la [configuration](https://github.com/GLF-OS/Nixos-by-GLF/blob/dev/nix-cfg/glf/gnome.nix), le bloc suivant installe gnome-software.

https://github.com/GLF-OS/Nixos-by-GLF/blob/e631e78df5ae682165af220f1f6ad6a9e1f41eaf/nix-cfg/glf/gnome.nix#L23-L39

Quelques lignes plus bas, on tente de l'exclure. 
https://github.com/GLF-OS/Nixos-by-GLF/blob/e631e78df5ae682165af220f1f6ad6a9e1f41eaf/nix-cfg/glf/gnome.nix#L44-L62

Sauf erreur, l'intention initiale était de l'exclure une fois `easy flatpak` disponible ce qui déjà le cas.

> [!NOTE]
> Avant de supprimer les deux mentions, vérifier si gnome-software est installé par défaut via l'option gnome

**Comment by camini** [comment]
gnome-software est bien installé nativement par le paquet gnome. Il faut donc l'exclure des paquets gnome.

**Comment by CORAAL** [comment]
> gnome-software est bien installé nativement par le paquet gnome. Il faut donc l'exclure des paquets gnome.

Entendu. 

Est-ce que nous sommes quand même d'accord pour supprimer l'appel suivant pour installer `gnome-software` ? 

https://github.com/GLF-OS/Nixos-by-GLF/blob/e631e78df5ae682165af220f1f6ad6a9e1f41eaf/nix-cfg/glf/gnome.nix#L23-L39

**Comment by camini** [comment]
Yes sir!
