### ISSUE TITLE
Crash firefox en NVIDIA

### ISSUE THREAD

**Issue by camini** [GLF-OS/Nixos-by-GLF#52]
A l'instant T : Wayland+NVIDIA+Firefox ca match pas sous nixos.
On patch firefox à coup de variable d'env pour le faire tourner sous xwayland?
On installe un chromium en plus? ( qui donne accès au cloud gaming?)
Les deux?

**Comment by Angedestenebres** [comment]
Hey :cat: 

En dehors de Nvidia et même si j'aimerais vraiment qu'on garde Firefox en navigateur par défaut, ce n'est pas utilisable avec les services comme Xbox Cloud.

Donc dans tous les cas, il ne peut pas y avoir que Firefox. Ce qui a été proposé, c'est de le garder en navigateur et de mettre une base Chromium pour faire des Webapp pour le Xbox Cloud Gaming, Geforce Now et le truc d'Amazon (et autres si besoins).
