### ISSUE TITLE
Goverlay

### ISSUE THREAD

**Issue by camini** [GLF-OS/Nixos-by-GLF#53]
On en fait quoi de lui?

**Comment by CORAAL** [comment]
Quel était le problème exactement ? 

Il provoquait des problèmes de performances avec steam, rendait l'interface inacessible après un jeu ? 
(ou je confonds avec autre chose?)

Si c'est le cas, on peut toujours le garder installé mais le retirer des variables d'environnement pour qu'il ne se lance pas automatiquement ? L'utilisateur garde la possibilité de l'utiliser à ses risques et périls ?

**Comment by camini** [comment]
Alors en soit goverlay ne se lance pas avec les jeux , il est juste là pour configurer Mangohud.
Mais comme noux fournissons déjà la conf de mangohud...

Pour ce qui est des perfs en jeu et des "crashs" de steam, c'est clairement Mangohud le coupable et c'est lui qu'il faudrait peut être désactivé via la conf qu'on injecte pour l'avoir en ON tout le temps.
