### ISSUE TITLE
Totem cassé avec nvidia

### ISSUE THREAD

**Issue by camini** [GLF-OS/Nixos-by-GLF#55]
Je vais pas revenir sur les points au dessus, tout est good sauf le point GDM/plymouth
Du coup j'ai fais l'install sur mon desktop avec la nvidia :
- Mes films de vacances ( :) ) en mkv ne passent pas sur totem . En AMD ca roule.
![Capture d’écran du 2024-12-10 20-21-04](https://github.com/user-attachments/assets/38e6e2dc-b935-484a-a300-ff91e6fbdee3)

On le remplace par quoi du coup? Celuloid pour une meilleure intégration en GTK? ou VLC car tout le monde connait que ca?

_Originally posted by @camini in https://github.com/GLF-OS/Nixos-by-GLF/issues/19#issuecomment-2532669066_

**Comment by CORAAL** [comment]
Celuloid me va, c'est un frontend de mpv et l'expérience avec mpv a toujours été bonne en ce qui me concerne.
Si on a aucun problème avec celuloid, on l'ajoute. L'utilisateur a toujours la liberté d'ajouter vlc s'il préfère.

**Comment by CORAAL** [comment]
Pr associé : https://github.com/GLF-OS/Nixos-by-GLF/pull/58
