### ISSUE TITLE
Faut-il supprimer mangohud des variables de lancement dans steam (par défaut) ?

### ISSUE THREAD

**Issue by camini** [GLF-OS/Nixos-by-GLF#57]
Sur discord, plusieurs personnes remontent que MangoHUD provoque divers problèmes allant de Steam qui doit être relancé puisqu'il devient inaccessible, pertes de performances et autres joyeusetés.

**Comment by camini** [comment]
Pour avoir tester pas mal de choses ces derniers temps, je peux dire que steam a des comportements bizarre même quand mangohud n'est pas forcé dans la conf. (redemarrage obligatoire,etc..)

Quand aux pertes de perfs, je ne saurais dire.

**Comment by T13nou** [comment]
Je prends ma casque d'utilisateur lambda, mais je ne suis pas fan du mangohud forcé. Je m'en suis passé depuis bien des années sans vraiment en ressentir le besoin.

J'imagine que lorsque l'on bench c'est un must, mais perso je ne le shipperais pas par défaut.
