### ISSUE TITLE
Ajouter Chrome pour la prise en charge des jeux en streaming

### ISSUE THREAD

**Issue by CORAAL** [GLF-OS/Nixos-by-GLF#60]
Suite à cette discussion https://github.com/GLF-OS/Nixos-by-GLF/issues/34, nous pouvons ajouter google-chrome pour permettre aux joueurs en streaming de jouer. 

Note, la version flatpak semble nécessiter l'utilisation d'une commande `flatpak --user override --filesystem=/run/udev:ro com.google.Chrome`

Je n'ai pas vérifié n'ayant pas de compte, nous avons deux approches possibles : 

- Google chrome via nixpkgs, ça implique que tout le monde l'aura, même ceux qui ne le veulent pas. 
- Un service systemd qui vérifie si google-chrome est installé via flatpak et exécute la commande `flatpak --user override --filesystem=/run/udev:ro com.google.Chrome`. 
C'est pas super propre, mais c'est une idée.

**Comment by camini** [comment]
j'ai proposer une PR pour simplement ajouter chromium :)
