### ISSUE TITLE
Ajouts d'outils de base pour lsusb, lspci

### ISSUE THREAD

**Issue by CORAAL** [GLF-OS/Nixos-by-GLF#66]
Je viens de m'apercevoir en débugguant qu'il manquait des outils standard comme `usbutils`, `pciutils`.
Je les rajouterais dans la soirée

**Comment by camini** [comment]
Il faudrait aussi ajouter GIT , ne serait ce que pour utiliser le cron qui va update la config :D

**Comment by CORAAL** [comment]
Si je n'ai pas foiré mes tests, git est normalement déjà installé et le script fonctionne OOTB, mais nous pouvons quand même le déclarer pour être tranquille. :p 
Je m'en charge dans la journée

**Comment by CORAAL** [comment]
Tâches : 

- [ ] `pciutils`
- [ ] `usbutils`
- [ ] `git`
