### ISSUE TITLE
Thème GTK pour flatpak

### ISSUE THREAD

**Issue by CORAAL** [GLF-OS/Nixos-by-GLF#72]
Ajouter après l'installation de flathub un service exécutant : 

`flatpak install org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark`

**Comment by camini** [comment]
D'après mes tests, adw-gtk3 est une dépendance indirect de easyflatpak

**Comment by CORAAL** [comment]
Si le thème est déjà installé : ✅
