### ISSUE TITLE
comment activer le serveur d impression

### ISSUE THREAD

**Issue by tobal37** [GLF-OS/Nixos-by-GLF#82]
bonjour, j'ai installé GLF OS et j'avais impérativement besoin de mon imprimante. Donc j'ai fouillé, j'ai été dans /etc/nixos/glf/, j'ai constaté que vous aviez prévu imprimante.nix et j'ai vu qu'il y avait default.nix. Je l'ai ouvert et j'ai compris qu'il fallait déclarer imprimante.nix pour pouvoir utiliser l'imprimante. Je l'ai fait et j'ai fait nixos-rebuild switch pour appliquer mes modifications et ça fonctionne cordialement

**Comment by CORAAL** [comment]
Salut :D 

Nous avons ajouté une première itération de configuration pour prendre en charge par défaut les imprimantes, est-ce que tu peux nous en dire plus sur tes modifications (que l'on puisse améliorer la configuration) ? 

- Quelle configuration tu as rajouté (tu peux copier-coller directement) 
- Quelle modèle d'imprimante ? 
- Méthode de connexion à l'imprimante ? ( `usb`, `réseau`, ... )

Merci :p

**Comment by tobal37** [comment]
Alors dans votre fichier de configuration imprimante.nix j ai rien toucher j'ai juste rajouter ./imprimante.nix dans le fichier défaut.nix qui se trouve dans le dossier glf de la glf os

**Comment by tobal37** [comment]
Si non mon imprimante et une Epson et2850 et elle et connecter a mon réseau local  en wifi
