### ISSUE TITLE
Impossible d'ajouter des extensions gnomes

### ISSUE THREAD

**Issue by Etienne-TR** [GLF-OS/Nixos-by-GLF#84]
Le logiciel Extensions fourni par Gnome ne permet pas d'installer d'installer d'extensions supplémentaires mais seulement de configurer celles déjà installées.

Le mieux serait à mon avis de retirer des paquets la version actuelle pour utiliser cette version qui en plus est disponible en flatpak : https://flathub.org/apps/com.mattjakeman.ExtensionManager

**Comment by camini** [comment]
C'est un choix fait par l'équipe en effet .
Nous avons choisi des extensions afin de créer un impact visuel tout en donnant des fonctionnalités qui nous pensons être bénéfique pour l'user.
Nous avons fait le choix de ne pas utiliser le flatpak ExtensionManager car nous voulons laisser le choix a l'user de le faire ou non.
