### ISSUE TITLE
Aucun service d'impression / Recherche imprimante réseau

### ISSUE THREAD

**Issue by Etienne-TR** [GLF-OS/Nixos-by-GLF#86]
Dans Gnome > Paramètres > Imprimantes
```
Error - some settings cannot be unlocked

Aucun service d'impression

Le service d'impression semble ne pas être disponible
```

Imprimante Brother DCP L2660DW en réseau non détectée.

**Comment by tobal37** [comment]
Bonjour regarde cette issue https://github.com/GLF-OS/Nixos-by-GLF/issues/82

**Comment by camini** [comment]
Normalement résolu a la prochaine mise à jour de la config via l'update cöté user
