### ISSUE TITLE
Secure boot

### ISSUE THREAD

**Issue by Jean-Mich-Much** [GLF-OS/Nixos-by-GLF#93]
Bonjour,

Prévoyez-vous la prise en charge complète de Secure Boot, en particulier dans un dual boot Windows/Linux ? Pour moi, Secure Boot est crucial pour se protéger contre les attaques, notamment sous Windows. Lorsque je teste une distribution Linux, c'est la première chose que je vérifie.

J'utilise BitLocker et l'option anti-bootkits de Windows Defender, qui dépendent de Secure Boot, pour sécuriser mon système et des données sensibles sur mon PC principal, utilisé dans divers scénarios "réseaux et locaux".

Merci de votre réponse et du travail accompli.

**Comment by camini** [comment]
Secure-Boot et nixos , c'est un mélange très compliqué pour le moment.
Si la situation s'améliore ce côté on regardera pour ajouter cela mais en l'état ce n'est pas possible

**Comment by Jean-Mich-Much** [comment]
Merci pour la réponse 😊
